//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pm3.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PM3_DIALOG                  102
#define IDD_DLG_BMWH                    129
#define IDD_DLG_BMWH_SON                130
#define IDD_DLG_                        131
#define IDD_DLG_JBXX                    131
#define IDD_DLG_DALR                    133
#define IDD_DLG_GZQK                    134
#define IDD_DLG_SHGX                    136
#define IDD_DLG_BZ                      137
#define IDD_DLG_SHGX_EDIT               138
#define IDD_DLG_CXBJ                    140
#define IDD_DLG_GL                      145
#define IDD_DLG_LOGIN                   146
#define IDD_DLG_EDITPW                  147
#define IDD_DLG_ADDUSER                 148
#define IDD_DLG_DELUSER                 149
#define IDB_BITMAP1                     162
#define IDC_BTN_BMWH                    1000
#define IDC_BTN_DALR                    1001
#define IDC_BTN_CXBJ                    1002
#define IDC_BTN_TJ                      1003
#define IDC_BTN_GL                      1004
#define IDC_TAB1                        1004
#define IDC_TEXT_LX                     1005
#define IDC_LIST1                       1006
#define IDC_BTN_ADD                     1007
#define IDC_BTN_EDIT                    1008
#define IDC_BTN_DEL                     1009
#define IDC_BTN_QRTJ                    1010
#define IDC_EDIT_BM1                    1011
#define IDC_EDIT_NR1                    1012
#define IDC_BTN_CANCLE1                 1013
#define IDC_TEXT_CZ                     1014
#define IDC_EDIT_BM2                    1015
#define IDC_EDIT_NR2                    1016
#define IDC_BTN_QRXG                    1017
#define IDC_BTN_CANCLE2                 1018
#define IDC_TEXT_BM1                    1019
#define IDC_TEXT_BM2                    1020
#define IDC_TEXT_NR1                    1021
#define IDC_TEXT_NR2                    1022
#define IDC_EDIT1                       1024
#define IDC_EDIT_BZ                     1024
#define IDC_EDIT2                       1025
#define IDC_EDIT_ZGBM                   1025
#define IDC_EDIT_GX                     1025
#define IDC_SEARCH_NB                   1025
#define IDC_EDIT_PW                     1025
#define IDC_COMBO_BM                    1026
#define IDC_EDIT_NB                     1026
#define IDC_EDIT3                       1026
#define IDC_EDIT_MZ                     1027
#define IDC_COMBO_ZC                    1027
#define IDC_EDIT_BM                     1027
#define IDC_EDIT4                       1027
#define IDC_EDIT_XX                     1028
#define IDC_DATETIMEPICKER_RCSJ         1029
#define IDC_EDIT_ZC                     1029
#define IDC_EDIT_BIRTH                  1029
#define IDC_COMBO_WH                    1030
#define IDC_DATETIMEPICKER_SCRQ         1030
#define IDC_EDIT_HY                     1031
#define IDC_EDIT_JK                     1032
#define IDC_EDIT_SEX                    1033
#define IDC_EDIT_ZY                     1034
#define IDC_EDIT_ZW                     1035
#define IDC_EDIT_WH                     1035
#define IDC_EDIT_GZ                     1036
#define IDC_EDIT_RYXZ                   1037
#define IDC_EDIT_RYZT                   1038
#define IDC_EDIT_JG                     1039
#define IDC_EDITBM                      1039
#define IDC_EDIT_JLCF                   1040
#define IDC_EDIT_NAME                   1041
#define IDC_EDIT_SMWT                   1041
#define IDC_COMBO_SEX                   1042
#define IDC_EDIT_SCYJ                   1042
#define IDC_DATETIMEPICKER_BIRTH        1043
#define IDC_EDIT_JSPX                   1043
#define IDC_EDIT_ZZ                     1044
#define IDC_EDITZC                      1044
#define IDC_EDIT_ID                     1045
#define IDC_EDIT_RCSJ                   1045
#define IDC_EDIT_HKXZ                   1046
#define IDC_EDIT_SCRQ                   1046
#define IDC_EDIT_HKSZD                  1047
#define IDC_EDIT_XZZ                    1048
#define IDC_RADIO1                      1049
#define IDC_RADIO2                      1050
#define IDC_BTN_SEAR_JQ                 1051
#define IDC_BTN_SEAR_MH                 1052
#define IDC_BTN_FIRST                   1053
#define IDC_BTN_PRE                     1054
#define IDC_BTN_NEXT                    1055
#define IDC_BTN_LAST                    1056
#define IDC_BTN_DETAIL                  1057
#define IDC_BTN_EXIT                    1058
#define IDC_SEARCH_NAME                 1064
#define IDC_STATE                       1065
#define IDC_BTN_SAVE                    1067
#define IDC_BTN_EDITPW                  1076
#define IDC_BTN_ADDUSER                 1077
#define IDC_BTN_BACKUP                  1078
#define IDC_EDIT_UN                     1078
#define IDC_BTN_RECOVERY                1079
#define IDC_BTN_DELUSER                 1080
#define IDC_EDIT_CURRENT                1081
#define IDC_EDIT_PW2                    1083
#define IDC_BTN_PRINT_VIEW              1084
#define IDC_BTN_PRINT                   1085
#define IDC_STAT                        1085
#define IDC_IPADDRESS1                  1086
#define IDC_TREE1                       1087
#define IDC_SPLIT1                      1088
#define IDC_COMBO1                      1091

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
